function Q_roll = func_Q_roll(in1,in2,in3)
%func_Q_roll
%    Q_roll = func_Q_roll(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-07 17:51:49

F_N = in1(:,3);
F_f_y_prime = in1(:,2);
R = in3(:,3);
mu_roll = in3(:,5);
psi = in2(4,:);
theta = in2(5,:);
t2 = abs(F_N);
t3 = sign(F_f_y_prime);
t4 = cos(psi);
t5 = cos(theta);
t6 = sin(psi);
t7 = sign(theta);
t10 = 1.0./R;
t8 = t4.^2;
t9 = t6.^2;
Q_roll = [-mu_roll.*t2.*t3.*t6.*t10;mu_roll.*t2.*t3.*t4.*t10;0.0;mu_roll.*t2.*t3.*t5.*t7.*t8+mu_roll.*t2.*t3.*t5.*t7.*t9;0.0;mu_roll.*t2.*t3.*t7.*t8+mu_roll.*t2.*t3.*t7.*t9];
end
