function C = func_C(in1,in2)
%func_C
%    C = func_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-07 17:51:49

R = in2(:,3);
h = in2(:,2);
m = in2(:,1);
phi_dot = in1(12,:);
psi_dot = in1(10,:);
theta = in1(5,:);
theta_dot = in1(11,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = R.^2;
t5 = h.^2;
t6 = (m.*t3.*t4.*theta_dot)./2.0;
t7 = -t6;
C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,m.*t2.*t3.*t4.*theta_dot.*(-1.0./2.0)+(m.*t2.*t3.*t5.*theta_dot)./6.0,(m.*phi_dot.*t3.*t4)./4.0+(m.*psi_dot.*t2.*t3.*t4)./4.0-(m.*psi_dot.*t2.*t3.*t5)./1.2e+1,t7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7,(m.*psi_dot.*t3.*t4)./4.0,0.0],[6,6]);
end
