function J_C = func_J_C(in1,in2)
%func_J_C
%    J_C = func_J_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-07 17:51:49

R = in2(:,3);
psi = in1(4,:);
theta = in1(5,:);
t2 = cos(psi);
t3 = cos(theta);
t4 = sin(psi);
t5 = sign(theta);
t6 = sin(theta);
J_C = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-R.*t3.*t4.*t5,R.*t2.*t3.*t5,0.0,-R.*t2.*t5.*t6,-R.*t4.*t5.*t6,-R.*t3.*t5,-R.*t4.*t5,R.*t2.*t5,0.0],[3,6]);
end
