function dVdq = func_dVdq(in1,in2)
%func_dVdq
%    dVdq = func_dVdq(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-07 17:51:49

g = in2(:,4);
m = in2(:,1);
dVdq = [0.0;0.0;g.*m;0.0;0.0;0.0];
end
