function J_dot_C = func_J_dot_C(in1,in2)
%func_J_dot_C
%    J_dot_C = func_J_dot_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-07 17:51:49

R = in2(:,3);
psi = in1(4,:);
psi_dot = in1(10,:);
theta = in1(5,:);
theta_dot = in1(11,:);
t2 = cos(psi);
t3 = cos(theta);
t4 = dirac(theta);
t5 = sin(psi);
t6 = sign(theta);
t7 = sin(theta);
t8 = R.*t2.*t4.*theta_dot.*2.0;
t9 = R.*t4.*t5.*theta_dot.*2.0;
t10 = -t9;
J_dot_C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t10-R.*psi_dot.*t2.*t3.*t6+R.*t5.*t6.*t7.*theta_dot,t8-R.*psi_dot.*t3.*t5.*t6-R.*t2.*t6.*t7.*theta_dot,0.0,R.*psi_dot.*t5.*t6.*t7-R.*t2.*t3.*t6.*theta_dot,-R.*psi_dot.*t2.*t6.*t7-R.*t3.*t5.*t6.*theta_dot,R.*t4.*theta_dot.*-2.0+R.*t6.*t7.*theta_dot,t10-R.*psi_dot.*t2.*t6,t8-R.*psi_dot.*t5.*t6,0.0],[3,6]);
end
